name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      sys_func_test:
        required: true
        description: "System Test Tag"
        type: string
        default: "@system"
      e2e_func_test:
        required: true
        description: "E2E Test Tag"
        type: string
        default: "@e2e"
      e2e_func_ENV:
        required: true
        description: "E2E Functional Environment"
        type: choice
        default: "T2"
        options:
         - T2
         - T5

jobs:
  Security_Scans:
    name: Security Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low

      - name: Run SAST (Static Application Security Testing)
        run: |
          echo "Running SAST Scans..."
          # Add SAST tool commands here
          
      
  Build:
    name: Build and Publish
    needs: Security_Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: '[{"id": "github", "username": "kakkargaurav", "password": "${{ secrets.REPO_TOKEN }}"}]'
          
      - name: Dependency Tree
        run: mvn dependency:tree 
        
      - name: Publish package
        run: mvn deploy -Dmaven.test.skip          
        
  Deploy_BADEV_T4:
    name: Deploy
    needs: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [BADEV, T4]
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to ${{ matrix.environment }}
        run: |
          echo "Deploying to ${{ matrix.environment }}..."
          # Add deployment script here (e.g., kubectl, Terraform)

  Functional-Test:
    name: System Functional Tests
    needs: Deploy_BADEV_T4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Functional Test
        run: mvn -B clean test -Dorg.slf4j.simpleLogger.defaultLogLevel=warn

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "target/surefire-reports/TEST-*.xml"
        if: always()

      - uses: actions/upload-artifact@v4
        with:
          name: functional-report
          path: target/Extent

  Performance-Test:
    name: System Performance Tests
    needs: Deploy_BADEV_T4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Performance Test
        run: mvn gatling:test
        
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "target/gatling/**/js/assertions.xml"
        if: always()

      - uses: actions/upload-artifact@v4
        with:
          name: nft-report
          path: target/gatling

  Deploy_T2_T5_NFT:
    name: Deploy
    needs: [Functional-Test, Performance-Test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [T2, T5, NFT]
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to ${{ matrix.environment }}
        run: |
          echo "Deploying to ${{ matrix.environment }}..."
          # Add deployment script here

  E2E-Functional-Test:
    name: E2E Functional Tests
    needs: Deploy_T2_T5_NFT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: E2E Functional Test
        run: mvn -B clean test

      - uses: actions/upload-artifact@v4
        with:
          name: e2e-functional-report
          path: target/Extent

  E2E-Performance-Test:
    name: E2E Performance Tests
    needs: Deploy_T2_T5_NFT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: E2E Performance Test
        run: mvn clean gatling:test

      - uses: actions/upload-artifact@v4
        with:
          name: e2e-nft-report
          path: target/gatling

  deploy_stg:
    name: Deploy Staging
    needs: [E2E-Functional-Test, E2E-Performance-Test]
    runs-on: ubuntu-latest
    environment:
      name: STG
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to STG
        run: |
          echo "Deploying to STG..."
          # Add deployment script here

  Smoke-Tests:
    name: Smoke Tests
    needs: deploy_stg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Smoke Tests
        run: mvn -B clean test

      - uses: actions/upload-artifact@v4
        with:
          name: smoke-test-report
          path: target/Extent

  deploy_prod:
    name: Deploy Production
    needs: Smoke-Tests
    runs-on: ubuntu-latest
    environment:
      name: PROD
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to PROD
        run: |
          echo "Deploying to PROD..."
          # Add deployment script here
